### ISSUE TITLE
Identification of use case challenge #2

### ISSUE THREAD

**Issue by kadelakun** [NCATSTranslator/Clinical-Data-Committee-Tracking-Voting#1]

**Comment by karafecho** [comment]
The purpose of this issue is to brainstorm regarding the next clinical data use case "challenge" question.

**Comment by karafecho** [comment]
**What is the Translator product?**

**Domains**
• Target landscape
• Drug repurposing
• [Redefining disease]

**Questions**
• Explain
• Predict

**Results**
• Establish user trust by finding ground truths
• Surface novel associations

**Comment by karafecho** [comment]
*Candidate:* montelukast (leukotriene receptor antagonist) (allergy, asthma treatment)
 
*Boxed warning:* agitation, aggressive behavior, anxiety, irritability, difficulty paying attention, memory loss or forgetfulness, confusion, unusual dreams, hallucinations (seeing things or hearing voices that do not exist), repeating thoughts that you cannot control, depression, difficulty falling asleep or staying asleep, restlessness, sleep walking, suicidal thoughts or actions (thinking about harming or killing yourself or planning or trying to do so), or tremor (uncontrollable shaking of a part of the body)

*FDA notice:* https://www.fda.gov/news-events/press-announcements/fda-requires-stronger-warning-about-risk-neuropsychiatric-events-associated-asthma-and-allergy

*COHD:* 35,000 prescriptions for montelukast in 5-year cohort
5,364,781 (https://www.nature.com/articles/sdata2018273)

*ICEES:* presumably 0 prescriptions in cohort of ~160,000 patients with asthma and related common pulmonary disorders; i2b2 indicates 61,487 unique patients prescribed that drug from mid-2004 through the present; actual number in asthma+ cohort TBD

**Comment by karafecho** [comment]
*Gap analysis questions:*

1. General question: What are the short- and long-term risks (e.g., morbidities, adverse clinical outcomes) of chronic viral hepatitis C infection? More precise COHD question: What conditions are clinically observed with significantly increased prevalence in defined time windows following chronic viral hepatitis C infection? 
2. What chemical exposure events occurred in the year prior to the onset of asthma exacerbations among patients with asthma and related common pulmonary disorders?
3. What comorbidities are associated with prolonged hospitalization among patients with Augmentin-induced DILI?
4. What chemical exposures are associated with recurrent middle ear infections among patients with PCD?
5. What is the genetic profile that enables a specific patient to have a positive survival outcome (survival time > x days) given a cancer therapy?

**Comment by CaseyTa** [comment]
These aren't challenges themselves, but I have some thoughts on how COHD could be useful in various challenges, such as drug repurposing questions. In general, I prefer the COHD associations to not be used as independent hops within a query graph to find potential answers, but rather use the COHD associations to help rank potential answers found by an ARA through some other query. This can be thought of as a parallel path to the answer node in a knowledge graph. A few suggestions on how this can be used (the bold sections indicate which parts COHD may be able to contribute to):

Given a target condition and candidate drugs found by an ARA for repurposing:
1. Does the target condition have common **comorbidities** that the candidate drug is **contraindicated** for? (there is some signal for contraindications captured in COHD)
2. Does the target condition have **phenotypic traits** that may be exacerbated by the candidate drug? (this query in COHD isn't very distinct from the above since both diseases and phenotypes are rolled up together into the OMOP condition domain)
3. Does the target patient population commonly take other **medications** that have interactions with the candidate drug? 

Note: A significant association found in COHD could be used to help rank answers, but the lack of a returned association edge does not indicate that an association does not exist.

**Comment by karafecho** [comment]
Additional suggestions from Exposures Provider:

1. Among patients prescribed montelukast, what factors differentiate those with a diagnosis of depression (or anxiety) from those without a diagnosis of depression (or anxiety)?
2. What chemical exposures appear to be causally associated with a diagnosis of depression (or anxiety) among patients with asthma and related common respiratory disorders?
3. AOP: montelukast - depression (or anxiety)
4. Through what mechanism might leukotriene antagonists cause depression (or anxiety)?
5. In addition to depression (or anxiety), what other symptoms or phenotypes are associated with montelukast?

**Comment by jh111** [comment]
Simple: What diseases are associated with patients on montelukast?
Simple: What diseases are predictive of being treated with montelukast?
Simple: What drugs are predictive of being treated with montelukast?
Simple: What drugs are prescribed after being treated with montelukast?
Simple: What drugs are disproportionate prescribed after being treated with montelukast?
More interesting: What mechanisms/drugs/genes might connect montelukast with drugs that are disproportionately prescribed after being treated with montelukast?
More interesting: What mechanisms/drugs/genes might connect montelukast with phenothypes that are disproportionately diagnosed after being treated with montelukast?

**Comment by karafecho** [comment]
# Candidate #3: Designing cohort-based clinical “studies” for Translator [Multi-omics EHR Risk Provider]

**Comment by karafecho** [comment]
# Candidate No. 4: mendiKanren Real-world Use Cases [NCATS, Unsecret Agent]

(Also see [this doc](https://docs.google.com/document/d/15vKt0RiarZUIiBU9LK-s6QsnUppJzyOpfro3WYB2XQY/edit?usp=sharing))

1. acanthosis nigricans: Patient presented with acanthosis nigricans. Genomic sequencing revealed variants in multiple genes. Causal variant was a gain of function in EGFR. MediKanren recommended erlotinib. We compounded it as a topical cream with a specialist pharmacy, and the patient applied to one arm, but not the other. Significant reduction in the skin growths occurred on the treated arm.

2. severe ataxic episodes: Patient presented with ataxic episodes. Genomic sequencing revealed multiple variants. Causal variant was a missense mutation in the domain controlling degradation of RHOBTB2, hence making it a gain of function in RHOBTB2.  No direct RHOBTB2 inhibitors are known to exist, but several indirector downregulators of RHOBTB2 (via E2F1) do exist, and celecoxib showed a substantial reduction in ataxic episodes.

3. extreme developmental delay; non-ambulatory at age 5: Patient presented with multiple VUSes.  Causal variant was determined to be in MAPK8IP3, leading to predicted haploinsufficiency. Retinoic acid is a potent upregulator of MAPK8IP3.  6 months of treatment with vitamin A lead to patient standing and taking simple steps.  18 months of treatments led to patient walking freely under own power and notable cognitive gains.

**Comment by karafecho** [comment]
# Candidate No. 5: Clinical x Genetics [Genetics Provider]

*Please see #4.

**Comment by karafecho** [comment]
# Candidate No. 6: Rethink DILI use case?

Prior to the breast cancer use case, we had considered a DILI use case. At the time, Multi-omics EHR Provider and Clinical Data Provider were capable of answering questions related to DILI, but Exposures Provider was only semi-capable, as we had not yet stood-up our planned ICEES+ DILI instance. We were going to move forward regardless until we realized that a breast cancer use case was something that all of the clinical KPs (including Connections Hypothesis Provider) could contribute to.

However, Exposures Provider received an Augmentin DILI dataset from the international DILIN network just this past Tuesday, 3/16/2021. We should be able to expose the data via ICEES+ fairly quickly. As such, I'm inclined to rethink this use case.

Thoughts from others?
