### ISSUE TITLE
Data Modeling for likelihood/risk/prediction

### ISSUE THREAD

**Issue by Bassa1** [NCATSTranslator/Clinical-Data-Committee-Tracking-Voting#16]
Data source = EHR datasets(need a way to demo these features from EHR)

Data type = real-world evidence(has connotation of FDA use)
- Note: CHP has used real-world evidence predicate, but is not from EHR

Predicate = ??

Biolink relation = related_to
- associated_with_increased_likelihood_of_concurrent
--- associated_with_increased_likelihood_of_future
- associated_with_decreased_likelihood_of_concurrent
--- associated_with_decreased_likelihood_of_future

Methods: Supervised machine learning, logistic regression (or other methods in future)
- Contemporaneous (same time): Can be used to mean the likelihood of a drug being given to patients with the disease X (not necessarily that drug treats disease X)
- Predict 2 months out: associated with likelihood a disease will occur, or a drug will be prescribed
- Predict 2 years out: associated with likelihood a disease will occur, or a drug will be prescribed

Decisions for Clinical Data Team
- Predicate
- Relation

Decisions for Multiomics EHR Risk KP
- Cut-offs
--- No cut-offs for coefficient (have ARA)
--- No cut-offs for p-value > 0.1 (have ARA)
- Coefficient log odds, NOT +/-
- Two predicate NOT one (increased/decreased)

**Comment by karafecho** [comment]
Closing this ticket, as predicates are now in place to support likelihood/risk: `biolink:associated_with_increased_likelihood_of` and `biolink:associated_with_decreased_likelihood_of` ...
