### ISSUE TITLE
Consistent use of biolink:correlated_with in TRAPI queries and responses from KPs

### ISSUE THREAD

**Issue by southalln** [NCATSTranslator/Clinical-Data-Committee-Tracking-Voting#2]
```
{
  "message": {
    "query_graph": {
      "nodes": {
        "n00": {
          "id": "MONDO:0007254"
        },
        "n01": {
          "category": "biolink:Drug"
        }
      },
      "edges": {
        "e00": {
          "predicate": "biolink:correlated_with",
          "subject": "n00",
          "object": "n01"
        }
      }
    }
  }
}

```
e.g. COHD: the issue with how to represent our data as knowledge in Biolink is a common issue with the clinical KPs and one that we’re actively discussing with Matt and Richard. The discussion is on the bigger question of how to represent data and knowledge coming from clinical and contextual KPs, but it also involves the discussion of what predicates and what node identifiers should be used. We’ve made good headway within our small group and are about to seek input from the larger Translator group to make sure that the model Matt and Richard designed will be usable by other KPs and ARAs.
To answer your question more specifically regarding COHD, currently our only supported predicate types are biolink:correlated_with and its parent biolink:related_to (the same information represented in both predicates). Since COHD mines its edges from associations within observational clinical data, biolink:correlated_with is the most specific predicate that we can assert as knowledge, so we won’t have predicates like biolink:has_phenotype or biolink:treats. We could try to infer things like biolink:treats, but currently, there’s no way to distinguish a biolink:treats edge derived from inference from our KP vs a similarly stated biolink:treats edge derived from curated knowledge from another KP. We currently do not have genetic data in COHD.

**Comment by karafecho** [comment]
@sstemann : Yes, Debbi is creating one [here](https://github.com/NCATSTranslator/TCDC-Tracking-Voting). Thanks!

**Comment by karafecho** [comment]
Closing, replaced with #13.
