### ISSUE TITLE
May relay pitch

### ISSUE THREAD

**Issue by karafecho** [NCATSTranslator/Clinical-Data-Committee-Tracking-Voting#5]
Our May Relay goal will consider use cases of target landscaping and drug repurposing, with a specific focus on ensuring that provenance returned is sufficient for users’ needs and also to confirm that the current TRAPI specification is fit-for-purpose. Our September Relay goal is to have a feature-complete Translator system deployed into a primarily NCATS hosted production environment that can address questions in these two use case domains, giving us ample time to refine performance as we plan for our soft release for the formal presentations in December.

When developing your pitch, we would like these questions addressed: 

1.       What is the duration of your challenge? Keep in mind, the relay is scheduled from May 10 to May 14, 2021 with 11:00am-4:00pm core hours.  

2.       Who is the preferred audience/attendee/contributors? 

3.       Do you foresee potential overlap with any other WG/Committees? 

4.       How do you anticipate reporting out? (I.e. what is the proposed deliverable?)

5.      How does your challenge align with goals written in the FOA? 

Please email me and cc Tyler Beck your pitches by March 26, 2021.

**Comment by karafecho** [comment]
From Kara via Slack, 03.12.21:

As we discussed, NCATS has tasked all WGs and committees with putting forward a "just-fix-it" pitch for the May relay meeting (due March 26). I'm wondering how folks feel about a pitch related to clinical laboratory findings and mappings to HPO. Seems like that might provide an opportunity to (1) get a feel for the amount of effort involved with such an undertaking and (2) solicit feedback from the broader consortium regarding the value of such an effort. Thoughts?

See #3.

**Comment by karafecho** [comment]
Kara: +1

**Comment by kadelakun** [comment]
@ehinderer @GregHydeDartmouth @meghasin @CaseyTa @newgene @TriageDr @suihuang-ISB @KevinBretonnelCohen @flannick @stevencox @RichardBruskiewich @sierra-moxon @diatomsRcool @jh111 Hello all! Please remember to vote on this ticket by THIS WEDNESDAY! Thank you!

**Comment by diatomsRcool** [comment]
I'm sorry, what is being voted on here?

**Comment by kadelakun** [comment]
NCATS is asking each of the WGs/Committee to pitch "Just Fix It" challenges for the next relay. Above, Kara suggested a pitch related to clinical laboratory findings and mappings to HPO. We are seeking votes on that idea. @diatomsRcool

**Comment by flannick** [comment]
Is this related to https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/4?

I'm very interested in that one. So would support any pitch bringing us toward that.

**Comment by karafecho** [comment]
@flannick : yes, the pitch is related to #4, but also applies more generally to the integration of clinical KPs with the broader Translator ecosystem.

**Comment by ehinderer** [comment]
Are there other options to vote on, or are we to all pitch a suggestion and then vote?

**Comment by karafecho** [comment]
@ehinderer : Others are free to offer suggested pitches. Please do so!

I don't think the committee is restricted to one pitch, but I do think we want to make sure that enough folks are supportive of any pitches that are put forward.

**Comment by suihuang-ISB** [comment]
Sorry - but like @ehinderer and @diatomsRcool - I am not sure (a) what we are voting for - a _specific_ pitch suggestion that @karafecho proposed (where is it articulated) or a  _type_ of pitch (as circumscribed [above](https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/5#issuecomment-801338640)) -  and (b) where we should submit suggestion - just email to Tyler as indicated [[above ](https://github.com/NCATSTranslator/Clinical-Data-Committee-Tracking-Voting/issues/5#issue-830360753)]?

@karafecho can you clarify? Thanks!

**Comment by diatomsRcool** [comment]
I think I understand now. I think Kara's suggested pitch above is fine to move forward with. I vote "yes", unless someone else has a better idea.

**Comment by karafecho** [comment]
Apparently, I've created confusion with my request to 'vote' on a pitch for the May relay. @suihuang-ISB, we are not officially voting; rather, I am asking folks to provide an informal 'thumbs up' or 'thumbs down' to the proposed pitch on labs.  Other proposals are welcome, too. We just need to reach a decision on one or more pitches by Friday, so that I can forward the suggestions to Tyler on behalf of the committee. I apologize for the confusion. Hopefully, the goals here are clear now. If not, please let me know.
Thanks, all!

**Comment by qianzhu2018** [comment]
> @flannick : yes, the pitch is related to #4, but also applies more generally to the integration of clinical KPs with the broader Translator ecosystem.

@karafecho what's your plan to connect this pitch with #4? it will be great we can test out these two ideas at the same time during this relay. do you have any specific use case to drive this exercise? We can request more time (4 hours or more) for the proposed pitch with a broader scope, when you submit it. Thanks!

**Comment by rtroper** [comment]
I would be in favor of a pitch related to labs as Kara has proposed.

**Comment by karafecho** [comment]
In my mind, proposed use case #4 is related to the proposed May relay pitch on labs by way of phenotypes. We can discuss more tomorrow.

**Comment by karafecho** [comment]
Tally: 8 thumbs up

May Relay Challenge - Clinical Data Committee

Background: Clinical laboratory measures are challenging to capture in EHR data and integrate with the broader Translator ecosystem. Specifically, the interpretation of laboratory measures requires either (1) a LOINC code to determine what lab was performed + (2) the laboratory measure or value + (3) a reference range OR (1) a LOINC code + (2) a flag. Moreover, in order to integrate labs with Translator, these interpretations must be mapped to ontologies such as HPO. The LOINC2HPO tool supports a limited number of such mappings, but it is incomplete and was developed using data from UNC's asthma cohort, which might have introduced bias.

Description: The intent of this challenge is to: (1) develop one or more meaningful use-case questions that would leverage laboratory measurements, (2) get a feel for the amount of effort involved with further development of the LOINC2HPO tool, and (3) solicit feedback from the broader consortium regarding the value of such an effort. 

Duration: 2 hours

Preferred audience: members of the Clinical Data Committee, with representatives from each of the clinical KPs and all ARAs

Overlap with other working groups/committees: None foreseen

Proposed deliverables: (1) one or more use case questions that leverage clinical laboratory measurements, (2) a work plan and set of example mappings, and (3) an assessment of the value of this effort to the broader Translator program.

Alignment with FOA: The proposed challenges directly aligns with the stated intent of the funding opportunity, namely to "help researchers understand the pathophysiology of human disease; connect clinical observations with molecular etiology; and identify shared molecular etiologies underlying multiple diseases".

**Comment by rtroper** [comment]
Nice! I like this a lot. Thanks for putting it together. Also, for the record, I am interested in DILI and was wondering if that could be a good candidate for a more specific use case centering on labs. But, I'm open to others as well!

**Comment by karafecho** [comment]
Committee approved the relay challenge pitch, which Kara submitted to Tyler B.  on March 26, 2021.

**Comment by karafecho** [comment]
Response from NCATS:

Thank you for your May relay pitch submission! We appreciate the technical introspection. We have just a few questions/comments:

    What is the driving use case that will highlight how clinical data makes Translator better? 
    Another idea is to have a Clinical representative in every user-related session to gauge how the Clinical Data Committee could be an asset to them. 

 

Could you please provide us with a name for your Just Fix It session? We’d like a name other than the WG/Committee name. 

 

We would also like to remind all the session leaders that the focus should remain on the use-cases of Drug Repurposing and Target Landscape. Obviously, the clinical data directly suggesting repurposing opportunities for rare diseases might be limited, but expect that clinical data will still play an important role. We really need to consolidate around a couple of driving use cases for clinical data at this May relay meeting. If it doesn’t happen by the time of the Relay meeting, we may not have time to implement and demonstrate it in action.

 

By COB April 23, we would like to see a bullet-point agenda for your session. In addition, please include the names of any invitees from outside the Translator consortium that will be important for your session to function, and also anyone (specifically named) in the consortium who is deemed essential to the discussion.

**Comment by karafecho** [comment]
*Proposed response:*

Dear NCATS:

Thank you for your comments and suggestions regarding the May relay challenge pitch that the Clinical Data Committee put forward. Please see our responses below.

*1. What is the driving use case that will highlight how clinical data makes Translator better?*

We have been developing a use case on drug-induced liver injury (DILI, a rare outcome of drug exposure) that focuses on drug repurposing. We expect that this use case, when executed as a TRAPI query, will invoke several clinical and non-clinical KPs: Clinical Data Provider, Exposures Provider, Multi-omics EHR Risk Provider, Connections Hypotheses Provider, and Genetics Provider. We are intentionally designing the use case such that it is generalizable and can extend to other diseases, as well as other applications such as drug target discovery.

We plan to have several specific use-case questions and TRAPI queries developed before the May relay.

*2. Another idea is to have a Clinical representative in every user-related session to gauge how the Clinical Data Committee could be an asset to them.*

Thank you for the suggestion. We will attempt to have committee representation on all user-related sessions, as well as any other sessions that might benefit from clinical representation.

*3.  Could you please provide us with a name for your Just Fix It session? We’d like a name other than the WG/Committee name.*

We are suggesting "Leveraging Clinical Labs as a New Source of Phenotype Data for Translator: DILI as an Initial Use Case".

*4. Bullet-point agenda and names of essential session attendees*

Given the comments and suggestions above, as well as the feedback that NCATS provider to Kara by way of the SRI, we are requesting that we can extend the session to 4 hours so that we may accomplish a broader set of goals than originally intended.

Title: Leveraging Clinical Labs as a New Source of Phenotype Data for Translator

Duration: 4 h

Agenda:

1. Overview of use case, use-case questions, and TRAPI queries for guests, ARA representatives, and ARS representative
2. Execution of TRAPI queries, revisions as needed [in parallel with (3)]
3. Deep dive of LOINC2HPO tool as a new source of phenotype data [in parallel with (2)]
4. Evaluation of TRAPI results
5. Summary and discussion of next steps

Essential attendees:

TBD

Thanks, again, for your feedback. We look forward to the May relay.

Best,

Kara, on behalf of the Translator Clinical Data Committee

**Comment by rtroper** [comment]
This sounds great

**Comment by karafecho** [comment]
Thanks, Ryan!

**Comment by karafecho** [comment]
Submitted to Tyler (copied Debbi and Qian).
